### ISSUE TITLE
Refactor of CLI and PersistentStorageController

### ISSUE THREAD

**Issue by OliFryser** [WilliamHeidemann/GitInsight#91]

**Comment by A-Guldborg** [comment]
#95 should be the last changes necessary. Read comment on #95 for details on what is needed.

**Comment by A-Guldborg** [comment]
`GetFrequencyMode` and `GetAuthorMode` are now being tested.
These include testing the private methods `GroupCommitsByDate`, `GroupByAuthor` and `GetCommits`.
Note that tests does not pass on Github Actions due to the error reported in #94 regarding unzipping repos.

Classes have changed to use `GetFrequencyMode` and `GetAuthorMode`.
We should test the two printing methods in GitInsight.CLI. 
 
`FindAllCommitsAsync` is now deprecated and *only* used in tests. Same goes for the GitCommitTracker. We should work on removing these methods and change the tests to use the new methods if applicable. All this should be done before this pull request is merged.
